version: "3.9"

services:
  postgres:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: book_database
    ports:
      - "5432:5432"
  
  fastapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
